# Generated by Django 2.2 on 2021-01-13 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_order_billing_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
