# Generated by Django 2.2 on 2021-01-13 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_billingaddress_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
