# Generated by Django 2.2 on 2021-01-20 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20210120_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='payment_option',
            field=models.CharField(choices=[('S', 'Stripe'), ('C', 'Cash on delivery')], default='C', max_length=30),
            preserve_default=False,
        ),
    ]
