# Generated by Django 2.2 on 2021-01-20 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_billingaddress_payment_option'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingaddress',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='last_name',
            field=models.CharField(default='Ahmed', max_length=100),
            preserve_default=False,
        ),
    ]
